name: CI

on: 
  schedule:
    - cron: "0 */12 * * 1"
  push: 

jobs:
  build_x86_msvc:
    name: Build on Windows MSVC (x86)

    runs-on: windows-latest

    steps:
      - uses: ilammy/msvc-dev-cmd@v1.0.0
        with:
          arch: "x86"
        name: "Setup PATH"

      - uses: actions/checkout@v1
        with:
          repository: ValleyBell/SMPSPlay
          ref: refs/heads/master
          submodules: true
      - uses: actions/checkout@v1
        name: "Download SMPSPlay code"
      - run: "cd ../SMPSPlay/libs; dir ../../smpsplay-ghact-test; copy ../../smpsplay-ghact-test/builder_fix.bat; ./builder_fix.bat; cd .."
        name: "Build libs"
      - run: "msbuild SMPSPlay.sln /p:PlatformToolset=v142"
        name: "MSBuild"
      - run: "dir"
        name: "todo: check output directory"
        
