on: 
  schedule:
    - cron: "0/20 0,4,6,12,18,20,22 * * *" # kinda doesn't work
  push: 

jobs:
  build_all:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/feature # latest branch
          repository: "RhenaudTheLukark/CreateYourFrisk"
          path: "cyf" # $GITHUB_WORKSPACE/cyf
      - uses: seanmiddleditch/gha-setup-vsdevenv@v1
        with:
          # List of components required in the selected VS installation (semi-colon separated)
          components: Microsoft.VisualStudio.Component.VC.Tools.x86.x64;Component.UnityEngine.x64
      - uses: actions/setup-python@v1.1.1
      - run: "cd $Env:GITHUB_WORKSPACE/cyf; python3 build.py"
