name: CI

on: 
  schedule:
    - cron: "0 */12 * * 1" # kinda doesn't work
  push: 

jobs:
  # msvc
  build_win32_msvc:
    name: Build on MSVC (Win32)
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1.0.0
        with:
          arch: "x86"
        name: "Setup PATH"
      - uses: actions/checkout@v1
        with:
          repository: ValleyBell/SMPSPlay
          ref: refs/heads/master
          submodules: true
        name: "Download SMPSPlay code"
      - uses: actions/checkout@v1
      - run: "cd ../SMPSPlay/libs; copy ../../smpsplay-ghact-test/builder_fix.bat; ./builder_fix.bat; cd .."
        name: "Build libs"
      - run: "cd ../SMPSPlay; msbuild SMPSPlay.sln /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=Win32"
        name: "MSBuild"
      - uses: actions/upload-artifact@v1
        with:
            name: SMPSPlay-msvc-x86
            path: ../SMPSPlay/Release/SMPSPlay.exe
  build_x64_msvc:
    name: Build on MSVC (x64)
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1.0.0
        with:
          arch: "x64"
        name: "Setup PATH"
      - uses: actions/checkout@v1
        with:
          repository: ValleyBell/SMPSPlay
          ref: refs/heads/master
          submodules: true
        name: "Download SMPSPlay code"
      - uses: actions/checkout@v1
      - run: "cd ../SMPSPlay/libs; copy ../../smpsplay-ghact-test/builder_fix_x64.bat; ./builder_fix_x64.bat; cd .."
        name: "Build libs"
      - run: "cd ../SMPSPlay; msbuild SMPSPlay.sln /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=x64"
        name: "MSBuild"
      - uses: actions/upload-artifact@v1
        with:
            name: SMPSPlay-msvc-x64
            path: ..\SMPSPlay\x64\Release\SMPSPlay64.exe
  # gcc
  build_i686_gcc:
    name: Build on GCC (i686)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: ValleyBell/SMPSPlay
          ref: refs/heads/master
          submodules: true
        name: "Download SMPSPlay code"
      - uses: actions/checkout@v1
      - run: "cd ../SMPSPlay; copy ../smpsplay-ghact-test/build_fix.diff; git apply build_fix.diff"
        name: "libvgm reference fixes"
      - run: "choco install mingw --x86 --force -y"
        name: "install x86 toolchain"
      - run: "cd ../SMPSPlay/libs; sh -c 'CFLAGS=\"-m32\" CXXFLAGS=\"-m32\" CMAKE_C_COMPILER=\"i686-w64-mingw32-gcc\" CMAKE_CXX_COMPILER=\"i686-w64-mingw32-g++\" CC=\"i686-w64-mingw32-gcc\" CXX=\"i686-w64-mingw32-g++\" ./build_libs_GCC.sh'"
        name: "Build libs"
      - run: "cd ../SMPSPlay; sh -c 'CFLAGS=\"-m32\" CXXFLAGS=\"-m32\" CC=\"i686-w64-mingw32-gcc\" CXX=\"i686-w64-mingw32-g++\" mingw32-make'"
        name: "GMake"
      - uses: actions/upload-artifact@v1
        with:
            name: SMPSPlay-gcc-x86
            path: ..\SMPSPlay\smpsplay.exe
  build_x86_64_gcc:
    name: Build on GCC (x86_64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: ValleyBell/SMPSPlay
          ref: refs/heads/master
          submodules: true
        name: "Download SMPSPlay code"
      - uses: actions/checkout@v1
      - run: "cd ../SMPSPlay; copy ../smpsplay-ghact-test/build_fix.diff; git apply build_fix.diff"
        name: "libvgm reference fixes"
      - run: "cd ../SMPSPlay/libs; sh -c 'CFLAGS=\"-m64\" CXXFLAGS=\"-m64\" CMAKE_C_COMPILER=\"x86_64-w64-mingw32-gcc\" CMAKE_CXX_COMPILER=\"x86_64-w64-mingw32-g++\" CC=\"x86_64-w64-mingw32-gcc\" CXX=\"x86_64-w64-mingw32-g++\" ./build_libs_GCC.sh'"
        name: "Build libs"
      - run: "cd ../SMPSPlay; sh -c 'CFLAGS=\"-m64\" CXXFLAGS=\"-m64\" CC=\"x86_64-w64-mingw32-gcc\" CXX=\"x86_64-w64-mingw32-g++\" make'"
        name: "GMake"
      - uses: actions/upload-artifact@v1
        with:
            name: SMPSPlay-gcc-x64
            path: ..\SMPSPlay\smpsplay.exe
  test_linux_gcc:
    name: Test build on GCC (Linux x86_64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: ValleyBell/SMPSPlay
          ref: refs/heads/master
          submodules: true
        name: "Download SMPSPlay code"
      - uses: actions/checkout@v1
      - run: "cd ../SMPSPlay && cp ../smpsplay-ghact-test/build_fix.diff . && git apply build_fix.diff"
        name: "libvgm reference fixes"
      - run: "cd ../SMPSPlay/libs && chmod +x build_libs_GCC.sh && ./build_libs_GCC.sh"
        name: "Build libs"
      - run: 'cd ../SMPSPlay && export USE_ALSA=0 && export USE_LIBAO=0 && export USE_BSD_AUDIO=1 && make'
        name: "GMake"
