name: CI

on: 
  schedule:
    - cron: "0 */12 * * 1"
  push: 

jobs:
  build_win32_msvc:
    name: Build on MSVC (Win32)
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1.0.0
        with:
          arch: "x86"
        name: "Setup PATH"
      - uses: actions/checkout@v1
        with:
          repository: ValleyBell/SMPSPlay
          ref: refs/heads/master
          submodules: true
      - uses: actions/checkout@v1
        name: "Download SMPSPlay code"
      - run: "cd ../SMPSPlay/libs; copy ../../smpsplay-ghact-test/builder_fix.bat; ./builder_fix.bat; cd .."
        name: "Build libs"
      - run: "cd ../SMPSPlay; msbuild SMPSPlay.sln /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=Win32"
        name: "MSBuild"
      - uses: actions/upload-artifact@v1
        with:
            name: SMPSPlay-msvc-x86
            path: ../SMPSPlay/Release/SMPSPlay.exe
  build_x64_msvc:
    name: Build on MSVC (x64)
    runs-on: windows-latest
    steps:
      - uses: ilammy/msvc-dev-cmd@v1.0.0
        with:
          arch: "x64"
        name: "Setup PATH"
      - uses: actions/checkout@v1
        with:
          repository: ValleyBell/SMPSPlay
          ref: refs/heads/master
          submodules: true
      - uses: actions/checkout@v1
        name: "Download SMPSPlay code"
      - run: "cd ../SMPSPlay/libs; copy ../../smpsplay-ghact-test/builder_fix_x64.bat; ./builder_fix_x64.bat; cd .."
        name: "Build libs"
      - run: "cd ../SMPSPlay; msbuild SMPSPlay.sln /p:PlatformToolset=v142 /p:Configuration=Release /p:Platform=x64"
        name: "MSBuild"
      - uses: actions/upload-artifact@v1
        with:
            name: SMPSPlay-msvc-x64
            path: ..\SMPSPlay\x64\Release\SMPSPlay64.exe
  # gcc
  build_x86_gcc:
    name: Build on GCC (x86)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: ValleyBell/SMPSPlay
          ref: refs/heads/master
          submodules: true
      - uses: actions/checkout@v1
        name: "Download SMPSPlay code"
      - run: "cd ../SMPSPlay; copy ../smpsplay-ghact-test/build_fix.diff; git apply build_fix.diff"
        name: "library building fixes"
      - run: "cd ../SMPSPlay/libs; sh -c 'CFLAGS=\"-m32\" && ./build_libs_GCC.sh'"
        name: "Build libs"
      - run: "cd ../SMPSPlay; cmd /c 'set CFLAGS=\"-m32\" && set CXXFLAGS=\"-m32\" && make'"
        name: "GMake"
      - run: "cd ../SMPSPlay; dir"
  build_x64_gcc:
    name: Build on GCC (x64)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          repository: ValleyBell/SMPSPlay
          ref: refs/heads/master
          submodules: true
      - uses: actions/checkout@v1
        name: "Download SMPSPlay code"
      - run: "cd ../SMPSPlay; copy ../smpsplay-ghact-test/build_fix.diff; git apply build_fix.diff"
        name: "library building fixes"
      - run: "cd ../SMPSPlay/libs; sh -c 'CFLAGS=\"-m64\" && ./build_libs_GCC.sh'"
        name: "Build libs"
      - run: "cd ../SMPSPlay; cmd /c 'set CFLAGS=\"-m64\" && set CXXFLAGS=\"-m64\" && make'"
        name: "GMake"
      - run: "cd ../SMPSPlay; dir"
